import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "../components/navbar";
import Footer from "../components/footer";
import { AuthProvider } from "../components/AuthContext"; 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex min-h-screen flex-col bg-white">
        <AuthProvider>
          <Navbar />
          <main className="flex-grow container mx-auto px-4 ">{children}</main>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}